table IMDB
	lineageTag: 71834acd-68b9-447b-93a9-31279d78bf4c
	sourceLineageTag: [gold].[t_imdb]

	measure 'Avg Rating' =
			
			AVERAGE ( IMDB[avg_rating] )
		formatString: 0.0
		lineageTag: 6a2e45b0-5dec-4545-8f60-0b9a42128cdf

	measure 'Avg Runtime (mins)' =
			
			AVERAGE ( IMDB[runtime_min] )
		formatString: 0
		lineageTag: 065b9401-8ea6-41ef-a6ac-a49dc5fcbc76

	measure 'Box Office $' =
			
			SUM ( IMDB[box_office] )
		lineageTag: 73a56fdc-904a-4721-b676-c99e20fecd3e

		formatStringDefinition =
				VAR CurrentValue = SELECTEDMEASURE()
				VAR BaseFormat = "$#,0"
				VAR NumberFormat =
				    SWITCH(
				        TRUE(),
				        CurrentValue >= 1e9,
				        ",,,.#" & "B",
				        CurrentValue >= 1e6,
				        ",,." & "M",
				        CurrentValue>= 1e3,
				        ",." & "K"
				    )
				RETURN
				    BaseFormat & NumberFormat

	measure 'Data as of' =
			
			MAX ( IMDB[last_refresh_date] )
		formatString: dd-MMM-yyyy
		lineageTag: 4bec6678-879f-4da2-9798-6224c7b59f53

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Number of Votes' =
			
			SUM ( IMDB[num_votes] )
		formatString: #,0
		lineageTag: 129dad9e-7a53-4212-8718-9ddba097c619

	measure 'Title #' =
			
			COUNTROWS ( IMDB )
		formatString: #,0
		lineageTag: 0d9b0666-2c49-4104-9ed8-76a22c5313df

	measure 'IMDB Link' =
			
			"https://www.imdb.com/title/"
			    & SELECTEDVALUE ( IMDB[IMDB ID] ) & "/"
		lineageTag: c6f95d04-5f37-4f17-aad4-b33fc02396b9

	measure 'Font Color' =
			
			IF (
			    CALCULATE (
			        NOT ISEMPTY ( IMDB ),
			        KEEPFILTERS (
			            'IMDB'[Is Top Title] = "Y"
			        )
			    ),
			    "Green"
			)
		lineageTag: 77e5a161-fd20-4a7a-99c9-84fd4cf561cd

	column 'Popularity Rank'
		dataType: int64
		formatString: 0
		lineageTag: 220a4c52-15df-407c-bd96-cb90d0e4ba89
		sourceLineageTag: overall_popularity_rnk
		summarizeBy: none
		sourceColumn: overall_popularity_rnk

		annotation SummarizationSetBy = Automatic

	column 'IMDB ID'
		dataType: string
		lineageTag: 20cd3900-79f4-4ebf-906e-2001e41f64a8
		sourceLineageTag: tconst
		summarizeBy: none
		sourceColumn: tconst

	column 'Title Type'
		dataType: string
		lineageTag: 15eaab2b-fe74-43c7-b7d7-a3c7a64708d0
		sourceLineageTag: title_type
		summarizeBy: none
		sourceColumn: title_type

	column 'Primary Title'
		dataType: string
		lineageTag: af082e24-f276-43b6-8cb8-7cf637b3eded
		sourceLineageTag: primary_title
		summarizeBy: none
		sourceColumn: primary_title

	column 'Original Title'
		dataType: string
		lineageTag: 4b1117c7-737c-4aeb-b70c-c71867d1d7e1
		sourceLineageTag: original_title
		summarizeBy: none
		sourceColumn: original_title

	column 'Release Year'
		dataType: int64
		formatString: 0
		lineageTag: 021882a1-30d3-4023-b428-6756e0680a3c
		sourceLineageTag: yr
		summarizeBy: none
		sourceColumn: release_year

	column 'Is Adult'
		dataType: string
		lineageTag: bbd7c1ba-df81-4e8b-a669-a5d3c78a618f
		sourceLineageTag: is_adult
		summarizeBy: none
		sourceColumn: is_adult

	column runtime_min
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bb674835-a25d-43cd-bd23-ace0e882622b
		sourceLineageTag: runtime_min
		summarizeBy: sum
		sourceColumn: runtime_min

	column Generes
		dataType: string
		lineageTag: 7170c79c-9397-4804-a0bc-e7fd61969dae
		sourceLineageTag: genres
		summarizeBy: none
		sourceColumn: genres

	column avg_rating
		dataType: double
		isHidden
		lineageTag: d649adcc-3499-4638-baa6-b88d7b84ad2d
		sourceLineageTag: avg_rating
		summarizeBy: sum
		sourceColumn: avg_rating

	column num_votes
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e462b090-1809-4389-be62-3649ec717fd5
		sourceLineageTag: num_votes
		summarizeBy: sum
		sourceColumn: num_votes

	column box_office
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 520c9e74-214d-45c9-83ec-017d4eea7bb8
		sourceLineageTag: box_office
		summarizeBy: sum
		sourceColumn: box_office

	column 'Top 250 Movie Rank'
		dataType: int64
		formatString: 0
		lineageTag: 7a1548fc-7268-469d-a776-afd6f71fa4e0
		sourceLineageTag: top_250_rnk
		summarizeBy: none
		sourceColumn: top_250_movie_rnk

	column 'Is Top 1000 Movie'
		dataType: string
		lineageTag: 45558799-e1a5-4bfd-9b7c-d79b2faf8d38
		sourceLineageTag: is_top_1000_movies
		summarizeBy: none
		sourceColumn: is_top_1000_movie

	column Languages
		dataType: string
		lineageTag: 08faa8c8-6205-42d4-a7a4-585552c33923
		sourceLineageTag: language_lst
		summarizeBy: none
		sourceColumn: language_lst

	column Directors
		dataType: string
		lineageTag: 937aa027-9021-4890-998d-6186bbb85d11
		sourceLineageTag: director_lst
		summarizeBy: none
		sourceColumn: director_lst

	column Actors
		dataType: string
		lineageTag: 78ce061c-85f5-488c-8d20-a3423a3af50c
		sourceLineageTag: actor_lst
		summarizeBy: none
		sourceColumn: actor_lst

	column Actresses
		dataType: string
		lineageTag: 6e40e0f3-b0d6-442b-b7de-d5d1f623226a
		sourceLineageTag: actress_lst
		summarizeBy: none
		sourceColumn: actress_lst

	column last_refresh_date
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 8ac58084-7b16-4c72-b1fd-bad2f5fbefd9
		sourceLineageTag: last_refresh_date
		summarizeBy: none
		sourceColumn: last_refresh_date

	column 'Is Top Title'
		dataType: string
		lineageTag: 942cdbb0-76e5-4c1f-952a-03bbf6ccedb5
		sourceLineageTag: is_top_1000_movies
		summarizeBy: none
		sourceColumn: is_top_title

	column 'Top 250 TV Rank'
		dataType: int64
		formatString: 0
		lineageTag: b3ca707f-b61d-46fb-95a2-3ebbc1f84a02
		sourceLineageTag: top_250_rnk
		summarizeBy: none
		sourceColumn: top_250_tv_rnk

	column 'Top Indian Movie Rank'
		dataType: int64
		formatString: 0
		lineageTag: 9c794bb5-39cc-4822-b465-3b3519347efa
		sourceLineageTag: top_250_rnk
		summarizeBy: none
		sourceColumn: top_indian_movie_rnk

	column 'Top Malayalam Movie Rank'
		dataType: int64
		formatString: 0
		lineageTag: 3b08672e-a691-44ad-9e51-27de68918a9f
		sourceLineageTag: top_250_rnk
		summarizeBy: none
		sourceColumn: top_malayalam_movie_rnk

	column 'Top Tamil Movie Rank'
		dataType: int64
		formatString: 0
		lineageTag: 070eff5e-e2d7-4857-b9d2-c4d090692f8c
		sourceLineageTag: top_250_rnk
		summarizeBy: none
		sourceColumn: top_tamil_movie_rnk

	column 'Top Telugu Movie Rank'
		dataType: int64
		formatString: 0
		lineageTag: 1a406ca7-9e94-40c6-bfc1-e7091602bf21
		sourceLineageTag: top_250_rnk
		summarizeBy: none
		sourceColumn: top_telugu_movie_rnk

	column 'Top Title Rank'
		dataType: int64
		formatString: 0
		lineageTag: be063804-dbc9-4233-8482-fbd80593bc0d
		sourceLineageTag: overall_popularity_rnk
		summarizeBy: none
		sourceColumn: top_title_rnk

	partition IMDB = entity
		mode: directLake
		source
			entityName: t_imdb
			schemaName: gold
			expressionSource: OneLake

